name: Build Image
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:

    - name: Install Dependencies
      run: sudo apt-get update && sudo apt install coreutils p7zip-full qemu-user-static

    - name: Checkout CustomPiOS
      uses: actions/checkout@v2
      with:
        repository: 'guysoft/CustomPiOS'
        ref: devel
        path: CustomPiOS

    - name: Checkout Project Repository
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}
        path: repository

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Build React frontend
      run: pushd repository/naturewatch_camera_server/static/client && npm i -y && npm run build && popd

    # Raspbian build OS
    - name: Download Raspbian Image
      run: cd repository/os/image && wget -q -c --trust-server-names 'https://downloads.raspberrypi.org/raspbian_lite_latest'

    - name: Update CustomPiOS Paths
      run: cd repository/os && ../../CustomPiOS/src/update-custompios-paths

    - name: Copy NaturewatchCameraServer to CustomPiOS directory
      run: cp -r repository /tmp/NaturewatchCameraServer && rm -rf /tmp/NaturewatchCameraServer/os && rm -rf /tmp/NaturewatchCameraServer/naturewatch_camera_server/static/client/node_modules && mv /tmp/NaturewatchCameraServer repository/os/modules/naturewatchcamera/filesystem/home/pi/NaturewatchCameraServer && ls repository/os/modules/naturewatchcamera/filesystem/home/pi/NaturewatchCameraServer

    - name: Build Image
      run: export BASE_IMAGE_ENLARGEROOT=1200 && export AUTO_HOTSPOT_NAME=MyNaturewatch && export AUTO_HOTSPOT_PASSWORD=badgersandfoxes && sudo modprobe loop && cd repository/os && sudo bash -x ./build_dist

    - name: Copy Output
      run: cp ${{ github.workspace }}/repository/os/workspace/*.img electrolab-camera.img
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2.3.0
      with:
        path: electrolab-camera.img
